name: Rebuild images

on:
  push:
    paths:
      - "_imgchunks/ready.txt"

permissions:
  contents: write

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rebuild images
        run: |
          mkdir -p img
          cat _imgchunks/final-logo.*.txt | base64 -d > img/logo-base-hq.webp
          cat _imgchunks/final-dashboard.*.txt | base64 -d > img/dashboard-hq.webp
          cat _imgchunks/final-app.*.txt | base64 -d > img/app-hq.webp

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add img/
          git commit -m "Add high quality images"
          git push
